PathRWData = "{{.zkevm_path_rw_data}}"
L1URL = "{{.l1_rpc_url}}"
L2URL = "http://{{.l2_rpc_name}}{{.deployment_suffix}}:{{.zkevm_rpc_http_port}}"
AggLayerURL = "{{.agglayer_url}}"

ForkId = {{.zkevm_rollup_fork_id}}
IsValidiumMode = {{.is_cdk_validium}}

{{if eq .zkevm_rollup_fork_id "12"}}

{{else if eq .zkevm_rollup_fork_id "13"}}



{{else}}

{{end}}

SequencerPrivateKeyPath = "{{or .zkevm_l2_sequencer_keystore_file "/etc/cdk/sequencer.keystore"}}"
ContractVersions = "banana"
# Doesn't look like this is needed at the moment, but soon perhaps?
# ContractVersions = "durian"
ContractVersions = "banana"
ContractVersions = "elderberry"
L2Coinbase = "{{.zkevm_l2_sequencer_address}}"
ContractVersions = "{{.zkevm_rollup_fork_name}}"
L2Coinbase = "{{.zkevm_l2_sequencer_address}}"
SequencerPrivateKeyPassword = "{{.zkevm_l2_keystore_password}}"

AggregatorPrivateKeyPath = "{{or .zkevm_l2_aggregator_keystore_file "/etc/cdk/aggregator.keystore"}}"
AggregatorPrivateKeyPassword = "{{.zkevm_l2_keystore_password}}"
SenderProofToL1Addr = "{{.zkevm_l2_agglayer_address}}"
polygonBridgeAddr = "{{.zkevm_bridge_address}}"


RPCURL = "http://{{.l2_rpc_name}}{{.deployment_suffix}}:{{.zkevm_rpc_http_port}}"
WitnessURL = "http://{{.l2_rpc_name}}{{.deployment_suffix}}:{{.zkevm_rpc_http_port}}"

# This values can be override directly from genesis.json
rollupCreationBlockNumber = "{{.zkevm_rollup_manager_block_number}}"
rollupManagerCreationBlockNumber = "{{.zkevm_rollup_manager_block_number}}"
genesisBlockNumber = "{{.zkevm_rollup_manager_block_number}}"

[L1Config]
chainId = "{{.l1_chain_id}}"
polygonZkEVMGlobalExitRootAddress = "{{.zkevm_global_exit_root_address}}"
polygonRollupManagerAddress = "{{.zkevm_rollup_manager_address}}"
polTokenAddress = "{{.pol_token_address}}"
polygonZkEVMAddress = "{{.zkevm_rollup_address}}"

[L2Config]
GlobalExitRootAddr = "{{.zkevm_global_exit_root_address}}"

[SequenceSender.AvailDAConfig]
seed = ""
ws_api_url = "wss://turing-rpc.avail.so/ws"
http_api_url = "https://turing-indexer.avail.so"
bridge_api_url = "https://turing-bridge-api.fra.avail.so"
app_id = "23"
timeout = "2000s"

[Log]
Environment = "development"     # "production" or "development"
Level = "{{.global_log_level}}"
Outputs = ["stderr"]

[Aggregator]
Port = "{{.zkevm_aggregator_port}}"
RetryTime = "30s"
VerifyProofInterval = "10s"
GasOffset = 150000
SettlementBackend = "agglayer"
[Aggregator.DB]
Name = "{{.aggregator_db.name}}"
User = "{{.aggregator_db.user}}"
Password = "{{.aggregator_db.password}}"
Host = "{{.aggregator_db.hostname}}"
Port = "{{.aggregator_db.port}}"
EnableLog = false
MaxConns = 200

[AggSender]


# The initial block number from which to start syncing.CertificateSendInterval = "1m"
CheckSettledInterval = "5s"
# Default: 0
